import Header from "./components/Header/Header.jsx";
import ProgressBar from "./components/ProgressBar.jsx";
import { Providers } from "./redux/provider.jsx";
import "./page.css";
import SideBar from "./components/SideBar/SideBar.jsx";
import AuthUser from "./utils/AuthUser.jsx";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body
          className="light bg-[#e2e2e2c2]"
        >
            <ProgressBar />
            <Header /> 
            <div className="flex justify-center items-center">
                <AuthUser>
                  <div className="relative w-[15%] h-fit">
                    <SideBar />
                  </div>
                </AuthUser>
              <div className="w-[85%]">{children}</div>
            </div>
        </body>
      </html>
    </Providers>
  );
}
