import { UserProvider } from '@auth0/nextjs-auth0/client';
import Sidebar from '@/app/components/Sidebar/Sidebar.jsx'
import Rightsidebar from '@/app/components/Rightsidebar/Rightsidebar.jsx'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RouteLayout({ children }) {
  return (
      <UserProvider>
        <div className='relative top-2 flex gap-5 justify-center'>
          <Sidebar />
          {children}
          <Rightsidebar />
        </div>
      </UserProvider>
  );
}